name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install
        run: npm ci || npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

  frontend:
    name: Frontend (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: backend
    strategy:
      matrix:
        node: [18.x, 20.x]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci || npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: All good
        run: echo "Backend and Frontend CI completed."